### ISSUE TITLE
App store release assets

### ISSUE THREAD

**Issue by n8fr8** [onionshare/onionshare-ios#35]

**Comment by n8fr8** [comment]
[ios-app-store-assets.zip](https://github.com/onionshare/onionshare-ios/files/10219571/ios-app-store-assets.zip)

graphics in English, Chinese

should we add these into fastlane folder?

also need to have strings

**Comment by tladesignz** [comment]
- The resolution of the files is too big. They don't stick to any of the available ones: https://www.ios-resolution.com. I'll reduce them to 6.5" aka. 6.46" aka. "iPhone 11 Pro Max" resolution of 1242 x 2688 pixel, which is the default size which Apple suggests should always be there.

- What's the point of Chinese? China and hence Apple don't allow Tor on the App Store. Inspection will discover quickly, that OnionShare contains Tor. The image which says it contains Tor doesn't help, either.

**Comment by n8fr8** [comment]
There are overseas Chinese speakers who will have access. The point is to have the design assets regardless.

**Comment by tladesignz** [comment]
> There are overseas Chinese speakers who will have access. The point is to have the design assets regardless.

I doubt, overseas Chinese speaker will see that. With a Chinese Apple ID, you won't see it, because it's not going to be distributed on the Chinese App Store. With a US Apple ID, you won't see it, because you're going to be shown the English images.

Anyway, I added it to the repo for now.

**Comment by n8fr8** [comment]
There are plenty of Chinese speaking people with an international Apple ID. We should support all languages eventually.

**Comment by tladesignz** [comment]
In favour of #36.

**Comment by tladesignz** [comment]
Turns out, we definitely need "screenshots" for 4 device types, at least:

https://help.apple.com/app-store-connect/#/devd274dd925

- 6.5-inch (iPhone 14 Plus, iPhone 13 Pro Max, iPhone 12 Pro Max, iPhone 11 Pro Max, iPhone 11, iPhone XSMax, iPhone XR): 1284 x 2778 pixels
- 5.5-inch (iPhone 8 Plus, iPhone 7 Plus, iPhone 6s Plus): 1242 x 2208 pixels
- 12.9-inch (iPad Pro (2nd generation)) | 2732 x 2048 pixels
- 12.9-inch (iPad Pro (6th generation, 5th generation, 4th generation, 3rd generation)): 2732 x 2048 pixels

What we currently have is an ad image split over 4 6.5" images.

The 5.5" image could be done by reducing the height of the 6.5" images, but should really be generated from the original source, since it's just the height, which is reduced and so image elements should probably be rearranged slightly for a better fit.

The 12.9" devices could of course also use portrait images, but I suggest to put the content of the ad image on a single "screenshot" file in landscape.

The difference between the 2 versions is normally the iOS UI overlay (slider bar at the bottom which replaces the hardware button) and rounded corners. It'll be interesting, if Apple will actually make us do that overlay. Not sure, never used ad images instead of real screenshots.

Please note: "Screenshots" for other devices will be generated by scaling down these 4 base versions. An iPhone 5/SE is physically *much* smaller than an iPhone 8+, an iPad mini is *much* smaller than an iPad 12.9". (The current content should be ok, but JFI.)

@glenn-sorrentino, can you generate these additional "screenshots" from your source material? Thank you!

**Comment by glenn-sorrentino** [comment]
@tladesignz @n8fr8 Here you go! https://keybase.pub/glennsorrentino/onionshare/ios/app%20store/

**Comment by tladesignz** [comment]
Yay! That was quick. Thank you @glenn-sorrentino!

Note for next time: No alpha transparency allowed.

**Comment by tladesignz** [comment]
Apple review doesn't like, that the iPad image shows iPhones in it. They block release because of it. @glenn-sorrentino, can you rethink that image?

**Comment by glenn-sorrentino** [comment]
For now here's an image with no devices. We can update when I get a few tablet screenshots. 

![1_en-US](https://user-images.githubusercontent.com/28545431/217634040-c6b56498-af1b-48f9-8049-f32c325cf08b.png)
![1_zh-CN](https://user-images.githubusercontent.com/28545431/217634046-3c550326-03af-4adc-b675-d01af0222bf1.png)

**Comment by tladesignz** [comment]
Woah! Not sure, if they'll like that, but, damn, that was quick! Thank you!

**Comment by tladesignz** [comment]
Original app store review complaint:

> We noticed that your screenshots do not sufficiently show your app in use. Specifically, your 11-inch iPad screenshots show an iPhone device frame.
>
> To help users understand your app’s functionality and value, your screenshots should highlight your app's core concept. For example, a gaming app should feature screenshots that capture actual gameplay within the app.

I'm afraid, they're really not fond of the marketing images. I'll try your new versions anyway and let you know, if they decline again!

**Comment by glenn-sorrentino** [comment]
I'm charging my iPad now to get screenshots :)

**Comment by tladesignz** [comment]
Sorry, just added more info text from the complaint. Please reload, so you see my updated message.

We might need to do actual screenshots.

Let me know, which screens we should show and what to show on them. (E.g. provide demo assets.)

**Comment by tladesignz** [comment]
...so I can script a screenshot automation.

**Comment by glenn-sorrentino** [comment]
1. Empty
2. Populated (multiple files)
3. Starting 
4. Sharing

**Comment by glenn-sorrentino** [comment]
Here are updated images with the iPad form factor:
![1_en-US](https://user-images.githubusercontent.com/28545431/217670100-d26516c1-2c07-4156-8732-8b8f633443b5.png)
![1_zh-CN](https://user-images.githubusercontent.com/28545431/217670111-1ce99d13-bcdb-4880-9b0b-b75cb0fa6de5.png)

**Comment by tladesignz** [comment]
Great! Updated AppStore Connect with your latest images.

Hope, they'll accept it. If not, I will put a screenshot generation script together. In that case, I'd love a selection of demo assets, because I'm going to suck at selecting them. I'll let you know!

Closing for now.
