### ISSUE TITLE
Timeline for receive files, host a website, chat anonymously features

### ISSUE THREAD

**Issue by sdfinest** [onionshare/onionshare-ios#52]
Hello, do you know when the **_OnionShare iOS application_**; will have the following features available: **_receive files, host a website, chat anonymously?_** At the very least the capability to receive files is paramount for me. If there is an issue implementing these features on iOS I totally sympathize.

**Comment by sdfinest** [comment]
Whats the time frame?

**Comment by tladesignz** [comment]
> receive files

While it doesn't seem to make sense so much to have  a mobile run as a deaddrop server constantly, especially not on iOS, we're thinking about having the app be a download client, too, so users don't need to use a Tor-cappable browser: #43.

Would that help you?

> host a website

This is actually implemented for iOS, as it was easy to achieve, however, we decided against exposing this, since running a website from an iOS mobile seems kind of a weird idea. After all, OnionShare doesn't provide a stable address and iOS will cut all connections as soon as the device goes into sleep mode.

Can you explain what your intended use case would be? Or is this just because you feel annoyed, when the mobile app doesn't exactly have the same features as the desktop app?

> chat anonymously

Same again: on iOS, no app can serve as a continuously listening server. Apps get suspended, when the device goes in sleep mode. (At least, after a while.) So, running a chat server isn't really working.

There's better apps out there for chatting. Even for anonymous use.

I seriously cannot imagine a world where we would offer this feature on mobile. Your case would have to be extraordinarily convincing.

**Comment by sdfinest** [comment]
So, my main interest was the receiving file feature. As for the other 2 features (host a website &  chat anonymously);  I could care less whether these features become available on iOS. I guess I was more so curious as to why these features weren’t available on mobile versus desktop….. But what you said make sense as to why they weren’t implemented.
