### ISSUE TITLE
Empty State Position

### ISSUE THREAD

**Issue by glenn-sorrentino** [onionshare/onionshare-ios#7]
**Current**
The empty state for both Sharing and Website modes are positioned at the top of the viewport, creating excessive negative space in the UI

**Expected**
Centered in the viewport, with 2rem padding bottom to bring the action closer to the center of the screen.

![empty-state](https://user-images.githubusercontent.com/28545431/159765762-d1433702-75d9-4989-8b4c-610610b2d3f9.png)

**Comment by tladesignz** [comment]
Fixed with https://github.com/tladesignz/AdParticipesCumCepis/commit/6f1c451200ccc56bca7e5a9ba42a4cc2d379309a

Concepts like "rem" or "em" or the like are unknown in iOS.
There's only logical pixels (compared to physical, which is typically 2x since the invention of the "Retina Display").

Please play around with the next TestFlight and reopen, if you'd like to have the offset from the middle be changed a little more or less.
Consider other device sizes, too, though. There's a lot of moving parts (esp. image size, which needs to adapt to screen estate), which play a role in this, therefore, it might end up to never look perfectly the way you like it on all screen sizes.

See the linked commit to get an idea how the layout actually happens.
